baseURL = 'https://etcwhat.com/'
languageCode = 'en-us'
title = "/etc/what - Karim's notes on tech"
theme = "cactus"
googleAnalytics = "UA-115617184-1"

[menu]
[[menu.main]]
  identifier = 'content'
  name = 'content'
  title = 'content'
  url = '/posts/'
  weight = 30
[[menu.main]]
  identifier = 'about me'
  name = 'about me'
  title = 'about me'
  url = '/about/'
  weight = 50

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
