baseURL = 'https://etcwhat.com/'
languageCode = 'en-us'
title = "/etc/what - Karim's notes on tech"
theme = "cactus"
googleAnalytics = "UA-115617184-1"

[params]
  showProjectsList = false
  projectsUrl = "https://github.com/kkr16"
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

[menu]
[[menu.main]]
  identifier = 'content'
  name = 'content'
  title = 'content'
  url = '/posts/'
  weight = 30
[[menu.main]]
  identifier = 'about me'
  name = 'about me'
  title = 'about me'
  url = '/about/'
  weight = 50

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[[params.social]]
  name = "github"
  link = "https://github.com/kkr16"

[[params.social]]
  name = "email"
  link = "blog@etcwhat.com" 

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/karimroukoz/"
